import { StyleSheet, Platform, StatusBar } from "react-native";

export default StyleSheet.create({
  container: { flex: 1 },
  content: {
    padding: 20,
    paddingTop: Platform.select({
      ios: 60,
      android: (StatusBar.currentHeight || 0) + 8,
    }),
    paddingBottom: 40,
  },
  lockActionWrap: { paddingHorizontal: 20, marginBottom: 12 },
  lockCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#38B2AC",
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 12,
    elevation: 2,
    marginBottom: 5,
  },
  lockCardLeft: { flexDirection: "row", alignItems: "center", flex: 1 },
  lockIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#2D3748",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  lockText: { flex: 1 },
  lockTitle: {
    color: "#fff",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 16,
  },
  lockSubtitle: {
    color: "#E2E8F0",
    fontFamily: "Poppins_400Regular",
    fontSize: 12,
    marginTop: 4,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  title: { fontSize: 26, fontFamily: "Poppins_700Bold", color: "#1B263B" },
  subtitle: {
    fontSize: 13,
    fontFamily: "Poppins_400Regular",
    color: "#778DA9",
    marginTop: 4,
  },
  iconBox: {
    width: 56,
    height: 56,
    borderRadius: 14,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
  },
  section: { marginBottom: 18 },
  sectionTitle: {
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
    color: "#415A77",
    marginBottom: 8,
  },
  pickerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E9ECEF",
  },
  pickerText: { fontFamily: "Poppins_500Medium", color: "#1B263B" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: "#fff",
    maxHeight: "60%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingBottom: 18,
    paddingTop: 8,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 8,
  },
  modalLarge: {
    backgroundColor: "#fff",
    maxHeight: "85%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 8,
  },
  modalHandle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(0,0,0,0.12)",
    marginVertical: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    marginBottom: 8,
    textAlign: "left",
    paddingLeft: 4,
  },
  modalItem: {
    paddingVertical: 14,
    paddingHorizontal: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  modalItemText: {
    fontSize: 15,
    fontFamily: "Poppins_500Medium",
    color: "#1B263B",
    marginLeft: 12,
  },
  itemSeparator: { height: 1, backgroundColor: "#F1F5F9", marginLeft: 56 },
  modalClose: { marginTop: 12, alignItems: "center" },
  modalCloseText: { color: "#38B2AC", fontFamily: "Poppins_600SemiBold" },
  catIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  inputCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 8,
    borderWidth: 1,
    borderColor: "#E9ECEF",
  },
  input: { backgroundColor: "transparent", fontSize: 16 },
  currency: {
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    color: "#38B2AC",
  },
  hint: {
    marginTop: 8,
    color: "#778DA9",
    fontFamily: "Poppins_400Regular",
    fontSize: 12,
  },
  actionButton: { marginTop: 20, borderRadius: 12, overflow: "hidden" },
  disabledButton: { opacity: 0.6 },
  actionGradient: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 14,
    gap: 8,
  },
  actionText: {
    color: "#fff",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 16,
  },
  inputError: {
    color: "#E53E3E",
    fontFamily: "Poppins_400Regular",
    fontSize: 12,
    marginTop: 4,
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9ECEF",
    marginBottom: 8,
  },
  loadingText: {
    fontFamily: "Poppins_500Medium",
    color: "#38B2AC",
    fontSize: 14,
  },
  /* segmented mode switch */
  modeSwitch: {
    flexDirection: "row",
    backgroundColor: "#E6F3F0",
    padding: 4,
    borderRadius: 999,
    alignItems: "center",
    marginTop: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#D1ECE8",
  },
  modeOption: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  modeOptionActive: {
    backgroundColor: "#2C9A92",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
  },
  modeOptionPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.995 }],
  },
  modeOptionText: {
    fontFamily: "Poppins_500Medium",
    color: "#256A5A",
    fontSize: 13,
  },
  modeOptionTextActive: {
    color: "#fff",
  },
  helperText: {
    fontFamily: "Poppins_400Regular",
    color: "#718096",
    fontSize: 13,
    marginBottom: 8,
  },
});
